regions = "./regions"
secret = "aEXcED5xJ3"

[sideload]
bind_addr = "0.0.0.0:81"

[[proxies.bind]]
addr = "0.0.0.0:80"
tls = false
[[proxies.bind]]
addr = "0.0.0.0:443"
tls = false

[[certificates]]
domain = "localhost"
certs = "certs/fullchain.pem"
key = "certs/privkey.pem"