id = "central"

[debug]
print_routes = false

[hypertext]
sideload_ports = [":81"]
sideload_secured_ports = []
ports = [":8000"]
secured_ports = [":8443"]
force_https = false

[[hypertext.certificate]]
key = "./certs/privkey.pem"
pem = "./certs/fullchain.pem"

[hypertext.limitation]
max_body_size = 549_755_813_888 # 512 GiB
max_qps = -1

[paths]
configs = "./config"

[telemetry]
request_logging = true
capture_traces = true

[performance]
traces_limit = 256
prefork = false

[security]
sideload_trusted_proxies = ["localhost"]
credential = "e81f43f32d934271af6322e5376f5f59"
