id = "example-region"

[[locations]]
id = "example-sse"
host = ["localhost:8000"]
path = ["/sse"]
[[locations.destinations]]
id = "example-sse-destination"
uri = "http://localhost:5000?sse=enable"
[[locations.transformers]]
type = "replacePath"
options = { pattern = "/sse", value = "" }

[[locations]]
id = "example-websocket"
host = ["localhost:8000"]
path = ["/ws"]
[[locations.destinations]]
id = "example-websocket-destination"
uri = "http://localhost:8765"

[[locations]]
id = "example-location"
host = ["localhost:8000"]
path = ["/"]
[[locations.destinations]]
id = "example-destination"
uri = "files://test/data"