id = "example-region"

[[locations]]
id = "example-websocket"
host = ["localhost:8000"]
path = ["/ws"]
[[locations.destinations]]
id = "example-websocket-destination"
uri = "http://localhost:8765"

[[locations]]
id = "example-warden"
host = ["localhost:4321"]
path = ["/"]
[[locations.destinations]]
id = "example-warden-destination"

[[applications]]
id = "example-warden-app"
workdir = "test/data/warden"
command = ["node", "dist/server/entry.mjs"]
environment = ["PUBLIC_CMS=https://smartsheep.studio"]

# [[locations]]
# id = "example-location"
# host = ["localhost:8000"]
# path = ["/"]
# [[locations.destinations]]
# id = "example-destination"
# uri = "files://test/data"