id = "index"

[[locations]]
id = "root"
hosts = ["localhost"]
paths = ["/"]
[[locations.destinations]]
id = "static"
uri = "files://regions?index=index.html"

[[applications]]
id = "script"
exe = "./script.sh"
workdir = "regions"